### ISSUE TITLE
Read API token from file instead of environment variable 

### ISSUE THREAD

**Issue by pettijohn** [caddy-dns/cloudflare#35]
I am trying to spin up Caddy in a Docker container, passing a secret in the docker-compose file. Ref: https://docs.docker.com/engine/swarm/secrets/

Docker intentionally requires the contents of the secret to be in a file and not an environment variable. In a compose file it looks like:

```
services:
  reverseproxy:
    container_name: caddy
    build: .
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /shares/caddy/data:/data
      - /shares/caddy/config:/config
    secrets:
      - cloudflare-api-key
      
secrets:
  cloudflare-api-key:
    file: ./cloudflare-api-key.secret
```

At runtime, that copies the contents of the file ./cloudflare-api-key.secret into /run/secrets/cloudflare-api-key in a tmpfs in the container (ref docs linked above for explanation). 

Is it possible to pass the API token as a path to a file rather than an environment variable?

```
tls {
    dns cloudflare /run/secrets/cloudflare-api-key
}
```

**Comment by pettijohn** [comment]
Note I worked around this by putting the secret in a .env file instead, but as the Docker documentation argues, this is probably less secure than putting it in a secret file https://docs.docker.com/compose/environment-variables/

**Comment by pettijohn** [comment]
FWIW I tried to write this but since I've never worked with Go I have no idea what I'm doing and it didn't seem to work. I spent way too much time trying to understand how to replace a module to even make the code work. Anyway - here's a link to a broken/partial implementation: 

https://github.com/pettijohn/cloudflare/commit/39673a76fc821898cada5112c889d0b021c3d3a5

**Comment by mholt** [comment]
Can you use the `--envfile` flag to give Caddy the environment file that way? https://caddyserver.com/docs/command-line#caddy-run

**Comment by pettijohn** [comment]
This does work with some compose file magic. Overriding the entrypoint of the image is clunky as you can see but functional. 

```
services:
  reverseproxy:
    container_name: caddy
    build: .
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/site
      - /shares/caddy/data:/data
      - /shares/caddy/config:/config
    secrets:
      - cloudflare-api-key
    entrypoint: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--envfile", "/run/secrets/cloudflare-api-key"]

secrets:
  cloudflare-api-key:
    file: ./cloudflare-api-key.secret
```
